version: '3.0'

services:

  base:
    build:
      args:
        from: ubuntu:focal
      context: .
      dockerfile: base.Dockerfile
    image: andreaostuni/gym-gz:base

  # ======
  # MASTER
  # ======

  ci-master:
    build:
      args:
        from: andreaostuni/gym-gz:base
        gazebo_codename: dome
      context: .
      dockerfile: cicd-master.Dockerfile
    image: andreaostuni/gym-gz:ci-master

  pypi-master:
    build:
      args:
        from: andreaostuni/gym-gz:base
        gazebo_codename: dome
      context: .
      dockerfile: cicd-master.Dockerfile
    image: andreaostuni/gym-gz:pypi-master

  # =====
  # DEVEL
  # =====

  ci-devel:
    build:
      args:
        from: andreaostuni/gym-gz:base
        gazebo_codename: fortress
        CMAKE_BUILD_TYPE: Debug
      context: .
      dockerfile: cicd-devel.Dockerfile
    image: andreaostuni/gym-gz:ci-devel

  pypi-devel:
    build:
      args:
        from: andreaostuni/gym-gz:base
        gazebo_codename: fortress
        CMAKE_BUILD_TYPE: Release
      context: .
      dockerfile: cicd-devel.Dockerfile
    image: andreaostuni/gym-gz:pypi-devel

  # ====
  # DEMO
  # ====

  latest:
    build:
      args:
        from: andreaostuni/gym-gz:pypi-master
        branch: master
      context: .
      dockerfile: Dockerfile
    image: andreaostuni/gym-gz:latest

  nightly:
    build:
      args:
        from: andreaostuni/gym-gz:ci-devel
        branch: devel
        pip_options: --pre
      context: .
      dockerfile: Dockerfile
    image: andreaostuni/gym-gz:nightly
